Milestone 4 filtering
phylischumba/Bookstore-redux pull request #4
Opened 2020-10-02 12:59 UTC by ikraamg

[Live Link](https://bookstore-ip.herokuapp.com/)

In this milestone, we completed the following tasks:

Enhanced the Redux store by adding a filter property
Added a CategoryFilter component that renders a category selection
Implement HandleFilterChange method and logic for filtering the bookList

Please find our commit below,
Thank you.

2020-10-02 22:32 UTC, mosaaleb requested changes
#### Well done @ikraamg @Phylis05 :clap:

All requirements are handled, only one left. 

Please change the filter reducer default state value, and submit a new code review.

##### Muhammad Ebeid.

2020-10-02 22:32 UTC, mosaaleb commented on src/reducers/filter.js
> +const filterReducer = (state = '', action) => {
- [ ] state should default to `all`

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone4/ItDefaultsToAll.png)

2020-10-02 22:48 UTC, ikraamg commented
Hi @mosaaleb , i was just confused as to how should we keep the default of the filter reducer method to 'all' but also not have 'all' stored in the redux store. Is that not a contradiction in the requirements?

2020-10-03 16:09 UTC, jofer86 approved these changes
## `const PROJECT_STATUS = "APPROVED"` 🚀 🚀 🚀 
## :wave: :wave: Hello! I'm Jorge, and  I will be conducting this code review. Let me get a closer look 🔎 🔍 🔎 🔍 🕵🏼 
- All of the required changes are taken care off great job you may move along.
--------------------------------------------------------------------
**Rock on**  🤘🏼 
**_Jorge Fernando Rincón Figueroa._** 
Technical Support Engineer.

2020-10-03 16:25 UTC, merged